/****** Object:  Table [dv].[ValidationRuns]    Script Date: 11/7/2017 8:24:15 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dv].[ValidationRuns](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[CycleName] [NVARCHAR](32) NULL,
	[CycleTimestamp] [NVARCHAR](20) NULL,
	[BatchName] [NVARCHAR](53) NULL,
	[RunDate] [DATETIME] NULL,
	[ValidationSetID] [UNIQUEIDENTIFIER] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dv].[ValidationRuns] ADD  DEFAULT (GETDATE()) FOR [RunDate]
GO


